import type { Profile, Restaurant, Deal, StorySubmission, PointsTransaction, DealRedemption } from '@/types'

export const MOCK_USER: Profile = {
  id: 'mock-user-001',
  email: 'max@pistazz.io',
  full_name: 'Max Mustermann',
  avatar_url: null,
  role: 'guest',
  tier: 'silber',
  total_points: 2350,
  available_points: 1850,
  total_visits: 12,
  total_stories: 8,
  instagram_handle: 'maxmustermann',
  instagram_connected: true,
  phone: '+49 89 123456',
  city: 'München',
  onboarding_completed: true,
  created_at: '2025-01-15T10:00:00Z',
  updated_at: '2025-05-01T12:00:00Z',
}

export const MOCK_OWNER: Profile = {
  ...MOCK_USER,
  id: 'mock-owner-001',
  email: 'owner@pistazzkitchen.de',
  full_name: 'Maria Pistazz',
  role: 'restaurant_owner',
  tier: 'gold',
}

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-001',
    owner_id: 'mock-owner-001',
    name: 'Pistazz Kitchen',
    slug: 'pistazz-kitchen',
    type: 'restaurant',
    description: 'Das coolste Restaurant der Stadt! 🍕🍝 Mediterrane Küche mit modernem Twist.',
    logo_url: null,
    cover_url: null,
    address: 'Maximilianstraße 42',
    city: 'München',
    zip: '80331',
    latitude: 48.1351,
    longitude: 11.5820,
    phone: '+49 89 123456',
    email: 'hallo@pistazzkitchen.de',
    website: 'https://pistazzkitchen.de',
    instagram_handle: 'pistazzkitchen',
    google_place_id: null,
    opening_hours: {
      monday: { open: '11:00', close: '23:00' },
      tuesday: { open: '11:00', close: '23:00' },
      wednesday: { open: '11:00', close: '23:00' },
      thursday: { open: '11:00', close: '23:00' },
      friday: { open: '11:00', close: '00:00' },
      saturday: { open: '10:00', close: '00:00' },
      sunday: { open: '10:00', close: '22:00' },
    },
    points_per_story: 500,
    points_per_reel: 750,
    points_per_google_review: 300,
    points_per_receipt: 100,
    points_per_post: 400,
    stamp_card_enabled: true,
    stamp_card_total: 8,
    stamp_card_reward: 'Ein Dessert deiner Wahl gratis 🍮',
    primary_color: '#8BB06A',
    is_active: true,
    is_verified: true,
    is_featured: true,
    total_stories: 342,
    total_reach: 128400,
    total_customers: 189,
    avg_rating: 4.8,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
  },
  {
    id: 'rest-002',
    owner_id: 'mock-owner-001',
    name: 'Pistachio Bar',
    slug: 'pistachio-bar',
    type: 'bar',
    description: 'Craft Cocktails & Snacks 🍹 Der angesagteste Spot für After-Work!',
    logo_url: null,
    cover_url: null,
    address: 'Sendlinger Straße 15',
    city: 'München',
    zip: '80333',
    latitude: 48.1340,
    longitude: 11.5700,
    phone: '+49 89 654321',
    email: 'hallo@pistachiobar.de',
    website: null,
    instagram_handle: 'pistachiobar',
    google_place_id: null,
    opening_hours: {
      thursday: { open: '18:00', close: '02:00' },
      friday: { open: '18:00', close: '03:00' },
      saturday: { open: '18:00', close: '03:00' },
    },
    points_per_story: 500,
    points_per_reel: 750,
    points_per_google_review: 300,
    points_per_receipt: 100,
    points_per_post: 400,
    stamp_card_enabled: false,
    stamp_card_total: 8,
    stamp_card_reward: null,
    primary_color: '#E5B84C',
    is_active: true,
    is_verified: true,
    is_featured: false,
    total_stories: 124,
    total_reach: 48000,
    total_customers: 92,
    avg_rating: 4.6,
    created_at: '2025-02-01T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
  },
  {
    id: 'rest-003',
    owner_id: 'mock-owner-002',
    name: 'Green Garden Bistro',
    slug: 'green-garden-bistro',
    type: 'bistro',
    description: '🥗 Frische saisonale Küche & vegane Optionen. Gemütlich & nachhaltig.',
    logo_url: null,
    cover_url: null,
    address: 'Leopoldstraße 88',
    city: 'München',
    zip: '80802',
    latitude: 48.1580,
    longitude: 11.5820,
    phone: '+49 89 987654',
    email: null,
    website: null,
    instagram_handle: 'greengardenbistro',
    google_place_id: null,
    opening_hours: {},
    points_per_story: 500,
    points_per_reel: 750,
    points_per_google_review: 300,
    points_per_receipt: 100,
    points_per_post: 400,
    stamp_card_enabled: true,
    stamp_card_total: 10,
    stamp_card_reward: 'Kaffee und Kuchen gratis ☕',
    primary_color: '#6D9450',
    is_active: true,
    is_verified: false,
    is_featured: false,
    total_stories: 56,
    total_reach: 22000,
    total_customers: 44,
    avg_rating: 4.4,
    created_at: '2025-03-01T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
  },
]

export const MOCK_DEALS: Deal[] = [
  {
    id: 'deal-001',
    restaurant_id: 'rest-001',
    restaurant: MOCK_RESTAURANTS[0],
    title: '20% auf deine Rechnung 💰',
    description: 'Poste eine Instagram Story von deinem Besuch und zeige sie dem Kellner – du bekommst 20% Rabatt!',
    trigger: 'instagram_story',
    status: 'active',
    reward_type: 'discount_percent',
    reward_value: '20',
    points_required: 0,
    min_order_value: null,
    max_redemptions: null,
    max_per_user: 1,
    valid_from: null,
    valid_until: null,
    valid_days: [1, 2, 3, 4, 5],
    valid_hours_start: null,
    valid_hours_end: null,
    total_redemptions: 87,
    total_reach: 42000,
    sort_order: 1,
    image_url: null,
    badge_text: '20% Rabatt',
    badge_color: '#8BB06A',
    created_at: '2025-01-15T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
  },
  {
    id: 'deal-002',
    restaurant_id: 'rest-001',
    restaurant: MOCK_RESTAURANTS[0],
    title: 'Gratis Cocktail für Reel 🍹',
    description: 'Erstelle ein Reel in unserem Restaurant und erhalte einen Cocktail deiner Wahl GRATIS!',
    trigger: 'instagram_reel',
    status: 'active',
    reward_type: 'free_item',
    reward_value: 'Cocktail',
    points_required: 0,
    min_order_value: null,
    max_redemptions: 50,
    max_per_user: 1,
    valid_from: null,
    valid_until: null,
    valid_days: [0, 1, 2, 3, 4, 5, 6],
    valid_hours_start: null,
    valid_hours_end: null,
    total_redemptions: 23,
    total_reach: 18500,
    sort_order: 2,
    image_url: null,
    badge_text: 'Gratis!',
    badge_color: '#E5B84C',
    created_at: '2025-02-01T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
  },
  {
    id: 'deal-003',
    restaurant_id: 'rest-001',
    restaurant: MOCK_RESTAURANTS[0],
    title: 'Vorspeise gratis mit 500 Punkten 🥗',
    description: 'Löse 500 Punkte ein und genieße eine Vorspeise deiner Wahl kostenfrei!',
    trigger: 'stamp_card',
    status: 'active',
    reward_type: 'free_item',
    reward_value: 'Vorspeise',
    points_required: 500,
    min_order_value: null,
    max_redemptions: null,
    max_per_user: 3,
    valid_from: null,
    valid_until: null,
    valid_days: [0, 1, 2, 3, 4, 5, 6],
    valid_hours_start: null,
    valid_hours_end: null,
    total_redemptions: 41,
    total_reach: 0,
    sort_order: 3,
    image_url: null,
    badge_text: '500 Punkte',
    badge_color: '#577A3D',
    created_at: '2025-03-01T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
  },
  {
    id: 'deal-004',
    restaurant_id: 'rest-002',
    restaurant: MOCK_RESTAURANTS[1],
    title: '2-für-1 Cocktails nach Bewertung ⭐',
    description: 'Hinterlasse eine Google Bewertung und trinke den zweiten Cocktail gratis!',
    trigger: 'google_review',
    status: 'active',
    reward_type: 'bogo',
    reward_value: '2for1',
    points_required: 0,
    min_order_value: null,
    max_redemptions: null,
    max_per_user: 1,
    valid_from: null,
    valid_until: null,
    valid_days: [4, 5, 6],
    valid_hours_start: null,
    valid_hours_end: null,
    total_redemptions: 15,
    total_reach: 8400,
    sort_order: 1,
    image_url: null,
    badge_text: '2 für 1',
    badge_color: '#E86B5A',
    created_at: '2025-04-01T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
  },
]

export const MOCK_TRANSACTIONS: PointsTransaction[] = [
  { id: 'tx-001', user_id: 'mock-user-001', restaurant_id: 'rest-001', restaurant: MOCK_RESTAURANTS[0], type: 'earned', amount: 500, balance_after: 2350, reference_type: 'story_submission', reference_id: 'sub-001', description: 'Punkte für instagram_story', created_at: '2025-05-01T14:30:00Z' },
  { id: 'tx-002', user_id: 'mock-user-001', restaurant_id: 'rest-002', restaurant: MOCK_RESTAURANTS[1], type: 'earned', amount: 300, balance_after: 1850, reference_type: 'story_submission', reference_id: 'sub-002', description: 'Punkte für google_review', created_at: '2025-04-28T19:00:00Z' },
  { id: 'tx-003', user_id: 'mock-user-001', restaurant_id: 'rest-001', restaurant: MOCK_RESTAURANTS[0], type: 'spent', amount: 500, balance_after: 1550, reference_type: 'deal_redemption', reference_id: 'red-001', description: 'Deal eingelöst: Vorspeise', created_at: '2025-04-20T12:00:00Z' },
  { id: 'tx-004', user_id: 'mock-user-001', restaurant_id: 'rest-001', restaurant: MOCK_RESTAURANTS[0], type: 'earned', amount: 750, balance_after: 2050, reference_type: 'story_submission', reference_id: 'sub-003', description: 'Punkte für instagram_reel', created_at: '2025-04-15T18:00:00Z' },
  { id: 'tx-005', user_id: 'mock-user-001', restaurant_id: 'rest-003', restaurant: MOCK_RESTAURANTS[2], type: 'earned', amount: 500, balance_after: 1300, reference_type: 'story_submission', reference_id: 'sub-004', description: 'Punkte für instagram_story', created_at: '2025-04-10T13:00:00Z' },
]

export const MOCK_STORIES: StorySubmission[] = [
  { id: 'sub-001', user_id: 'mock-user-001', user: MOCK_USER, restaurant_id: 'rest-001', restaurant: MOCK_RESTAURANTS[0], type: 'instagram_story', status: 'approved', media_url: null, thumbnail_url: null, instagram_media_id: null, instagram_permalink: 'https://instagram.com/p/abc123', caption: 'Lecker beim Pistazz Kitchen! 🍕', verified_at: '2025-05-01T15:00:00Z', verified_by: 'mock-owner-001', rejection_reason: null, reach: 1240, impressions: 3400, likes: 89, points_awarded: 500, created_at: '2025-05-01T14:30:00Z', updated_at: '2025-05-01T15:00:00Z' },
  { id: 'sub-005', user_id: 'mock-user-002', restaurant_id: 'rest-001', type: 'instagram_reel', status: 'pending', media_url: null, thumbnail_url: null, instagram_media_id: null, instagram_permalink: 'https://instagram.com/reel/xyz789', caption: 'Amazing food! 🍝', verified_at: null, verified_by: null, rejection_reason: null, reach: 0, impressions: 0, likes: 0, points_awarded: 0, created_at: '2025-05-06T10:00:00Z', updated_at: '2025-05-06T10:00:00Z' },
  { id: 'sub-006', user_id: 'mock-user-003', restaurant_id: 'rest-001', type: 'google_review', status: 'pending', media_url: null, thumbnail_url: null, instagram_media_id: null, instagram_permalink: null, caption: '5 Sterne – absolut empfehlenswert!', verified_at: null, verified_by: null, rejection_reason: null, reach: 0, impressions: 0, likes: 0, points_awarded: 0, created_at: '2025-05-06T08:30:00Z', updated_at: '2025-05-06T08:30:00Z' },
]

export const MOCK_ADMIN_PROFILES: Profile[] = [
  { ...MOCK_USER, id: 'mock-user-001', full_name: 'Max Mustermann', email: 'max@example.com', total_points: 2350, total_stories: 8, total_visits: 12, tier: 'silber', created_at: '2025-01-15T10:00:00Z', updated_at: '2025-05-01T12:00:00Z' },
  { ...MOCK_USER, id: 'mock-user-002', full_name: 'Sarah Schmidt', email: 'sarah@example.com', total_points: 5800, total_stories: 24, total_visits: 31, tier: 'gold', created_at: '2025-02-01T10:00:00Z', updated_at: '2025-05-02T12:00:00Z' },
  { ...MOCK_USER, id: 'mock-user-003', full_name: 'Tom Bauer', email: 'tom@example.com', total_points: 890, total_stories: 3, total_visits: 4, tier: 'bronze', created_at: '2025-04-10T10:00:00Z', updated_at: '2025-04-28T12:00:00Z' },
  { ...MOCK_USER, id: 'mock-user-004', full_name: 'Lisa Wagner', email: 'lisa@example.com', total_points: 12400, total_stories: 52, total_visits: 67, tier: 'platin', created_at: '2024-11-01T10:00:00Z', updated_at: '2025-05-05T12:00:00Z' },
  { ...MOCK_USER, id: 'mock-user-005', full_name: 'Jonas Kraus', email: 'jonas@example.com', total_points: 1750, total_stories: 7, total_visits: 9, tier: 'silber', created_at: '2025-03-15T10:00:00Z', updated_at: '2025-04-30T12:00:00Z' },
]

export const MOCK_CHART_DATA = {
  stories7Days: [
    { date: 'Mo', stories: 4, reach: 2400 },
    { date: 'Di', stories: 7, reach: 4200 },
    { date: 'Mi', stories: 5, reach: 3100 },
    { date: 'Do', stories: 12, reach: 7800 },
    { date: 'Fr', stories: 18, reach: 12400 },
    { date: 'Sa', stories: 24, reach: 18600 },
    { date: 'So', stories: 15, reach: 9800 },
  ],
  dealsByTrigger: [
    { trigger: 'Story', count: 45 },
    { trigger: 'Reel', count: 23 },
    { trigger: 'Google', count: 18 },
    { trigger: 'Beleg', count: 31 },
    { trigger: 'Stempel', count: 12 },
  ],
  guestPie: [
    { name: 'Neue Gäste', value: 68 },
    { name: 'Wiederkehrend', value: 32 },
  ],
}

// Helper: check if we're in dev/mock mode (no real Supabase)
export const IS_MOCK_MODE =
  !process.env.NEXT_PUBLIC_SUPABASE_URL ||
  process.env.NEXT_PUBLIC_SUPABASE_URL.includes('placeholder')
